### ISSUE TITLE
look and feel updates

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/rocrate-to-pages#12]
suggested changes to make for https://data.ocean-sampling-day.org/OSD2018/ (and clearly all the other similar folders)
- [x] in the dark blue left-side menu, the filenames can be long: I'd like to be able to see the full name, perhaps that can pop up when you hover over it with a mouse?
- [x] the README.md is centre-formatted, please do left-side or even-length-lines formatting
- [x] The lists in these READMEs are for some reason with a shorter sentence length, could they please instead be just the same as the rest of the text
- [x] we see that when http's are in the text in the readme, in the github view they come up as links, but not here: can this be fixed or should we instead convert the text to explicitely be links (if that is even possible)?
- [ ] the "i" and the "map" symbol at the top right of all pages, could a popup be used when the mouse is over them to say what they are? i seems to send you back to the README for that folder, the map is a general github search link
- [ ] and instead of being an "all GitHub" search link, can this just be a search in the current space (i.e. OSD here)?
- [x] on https://data.ocean-sampling-day.org/OSD2018/#./QualityControlledData/ the readme text goes way below the pale blue box it is located in. that should not be

**Comment by cedricdcc** [comment]
@kmexter 
instead of being an "all GitHub" search link, can this just be a search in the current space (i.e. OSD here)?
_We still need to figure out how to insert the url of the github repo without actually knowing where it resides_

**Comment by kmexter** [comment]
In https://data.ocean-sampling-day.org/OSD2018/#./QualityControlledData/version2/ I 

- [ ] cannot see any more a listing of files in the dark blue menu on the left. Where have they gone?
- [ ] In that dark blue menu I can click on parent and root. I clicked on parent and get a page that is blank?
- [ ] The list in the readme is still centre-aligned. It needs to be left-aligned. Also, some of the list items are still too short, wrapping over at less than half-way thru the page length (best seen on https://data.ocean-sampling-day.org/OSD2018/#./QualityControlledData/version1/) 

In https://data.ocean-sampling-day.org/OSD2018/#./Documentation/

- [ ] Indeed the long filenames are visible via a popup when I hover over them - so fixed. 
- [ ] But here also the text in the lists is still centre-spaced rather than leftborder-aligned

In https://data.ocean-sampling-day.org/OSD2014/#./ 

- [ ] there is an https in the first line of the readme that is not coming up as a link: please tell me how I need to make this become a link (i.e. do I need to change the formatting of this string or can you make it come up as a link? Which is easier)
- [ ] the readme still goes way below the box it resides in

**Comment by kmexter** [comment]
points mentioned here have not all been resolved. Note that they should be before we onboard OSD on the marketplace.

**Comment by kmexter** [comment]
Tested again on https://data.ocean-sampling-day.org/OSD2018/

Good points
- I have rapidly gotten the hang of clicking on the left or main panels to see them only, so that works for me
- have rapidly understood what the 3 boxes are for (annotations, view, download) so that works for me
- the file that is the rocrate.json, could this not be specially flagged as "ro crate specification file" (or short for that) rather than "creative work"?
- I am not sure of the purpose of "hide info" and "show info". when I "hide info" I have a blank main panel - what is the point of that? Is this to make way for something that is yet to come?

Must fix
- [ ] I am confused about what I am looking at when I first go to https://data.ocean-sampling-day.org/OSD2018/. When I click on a subfolder, https://data.ocean-sampling-day.org/OSD2018/#./Documentation/, then I can see in the main panel at the top "show readme of folder documentation". Great: but why don't I see that same when I am on https://data.ocean-sampling-day.org/OSD2018/ - i.e. why can't I see the "show readme of folder OSD2018" there?  
- [ ] Text in the README is still centre-justified. This is when I click on the left menu and "view" the README. Why can't that view be the same as the "view" you get when you "show readme of folder xxx", because that one looks perfect? 
- [ ] Need a "go back" button or "go home" button when I am on the left-side menu and have clicked on a folder to see its contents - can't figure out how to go back to the main ro-crate 
- [ ] Would like to be able to collapse the listing in the left menu so I only see the subfolders of the ro-crate folder and its own contents, not all the files in each subfolder as well
- [ ] Is unclear how I can see or just get to the other repos /ro-crates in that github. I would like to be able to go up and sideways in the "ocean-sampling-day" space, and not be limited to only the "OSD2018" space. For that, I need to be able to get to the top-most repo of ocean-sampling-day. Is there a way you can see a navigateion of the entire github (is that what the "links" image in the left menu is for? Right now clicking on that does nothing for me)

Would be nice (either less important or are a should but can see may take a while to do)
- [ ] Would like to be able to drag-expand (and contract) the left menu
- [ ] Left menu have the title "OSD2018 RoCrate" where the "OSD2018" is the repo name. 
- [ ] Still cannot see the right side of the main panel when the left-panel is open. Either scroll bar or just let me resize my browser so I can see it? or compress the window? 

Should fix when must are done
- [ ] "Show/hide readme of folder: . " I would like to see the folder's name after the ": .". I can see this happens when I go to a subfolder, but not when I am on the ro-crate folder. I understand why this is: "." refers to the top-level directory) but it is user unfriendly  
- [ ] TSV files (as well as CSV) do not view, they only download 
- [ ] make the "search" case insensitive
- [ ] the listing of files, subfolders, and their subfolders, that I see when I first go to https://data.ocean-sampling-day.org/OSD2018/ in the main panel....it is incredibly long for this folder as there is a lot there and that really does impede my understanding of what is in this ro-crate. I would rather just see the files and subfolders listed, and not also the content of each of those subfolders
- [ ] On the left menu, the Resources --> ./ro-crate-metadata.json is at the bottom (probably alphabetical?): that particular file I think I'd like to see listed at the top
- [ ] For that ro-crate.json file, the "preview" does not show me the file, rather it shows me its annotations. Referring to the second point above: I think what I am seeing when I go to the URL is the content of the ro-crate, could that be it? But if I want to see the content of the ro-crate, then I can click on the ro-crate.json file and "view" it, I don't need to see it any other way.
